version: "3.8"

services: 
  identity:
    depends_on: 
      - mssql
    ports:
      - "5001:80"
  
  mssql:
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: "Qwerty123456!"
      MSSQL_PID: Express
    volumes:
      - mssql_data:/var/opt/mssql

volumes: 
  mssql_data: