version: "3.8"

services: 
  identity-service:
    depends_on: 
      - mssql
      - rabbitmq
    ports:
      - "5001:8080"
      - "5002:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnet.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    networks: 
      - elastic
      - mssql-network
      - api-gateway
      - rabbitmq-network
  
  book-service:
    depends_on: 
      - mssql
      - rabbitmq
    ports:
      - "5003:8080"
      - "5004:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnet.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - elastic
      - mssql-network
      - api-gateway
      - rabbitmq-network
      - redis-network
  
  review-service:
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - "5005:8080"
      - "5006:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnet.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - elastic
      - mongodb-network
      - api-gateway
      - rabbitmq-network
      - redis-network
        
  ocelot-api-gateway:
    depends_on:
      - identity-service
      - book-service
      - review-service
    ports:
      - "5010:8080"
      - "5000:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnet.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - elastic
      - api-gateway
      - rabbitmq-network
  
  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: "rabbitmq"
    networks:
      - rabbitmq-network
  
  redis:
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
      - REDIS_PASSWORD=1234
    networks:
      - redis-network
      
  
  mssql:
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: "Qwerty123456!"
      MSSQL_PID: Express
    volumes:
      - mssql-data:/var/opt/mssql
    networks: 
      - mssql-network
  
  mongodb:
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongodb-network
  
  elasticsearch:
    ports:
      - "9200:9200"
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/var/lib/elasticsearch/data
    networks: 
      - elastic
  
  kibana:
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks: 
      - elastic

networks:
  elastic:
    driver: bridge
  mssql-network:
    driver: bridge
  mongodb-network:
    driver: bridge
  api-gateway:
    driver: bridge
  rabbitmq-network:
    driver: bridge
  redis-network:
    driver: bridge

volumes: 
  mssql-data:
  elasticsearch-data:
  mongodb-data: