/**
 * Review.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import {Inject, Injectable, Optional} from '@angular/core';
import {HttpClient, HttpEvent, HttpHeaders, HttpResponse} from '@angular/common/http';

import {Observable} from 'rxjs';
import {gateway} from "../constants/endpoints";
import {ReviewResponseDto} from "../models/review/reviewResponseDto";
import {AddCommentToReviewDto} from "../models/review/addCommentToReviewDto";
import {DislikeReviewDto} from "../models/review/dislikeReviewDto";
import {LikeReviewDto} from "../models/review/likeReviewDto";
import {UpdateReviewDto} from "../models/review/updateReviewDto";
import {CreateReviewDto} from "../models/review/createReviewDto";

@Injectable({
  providedIn: 'root'
})
export class CriticReviewsService {

    protected basePath = gateway;
    public defaultHeaders = new HttpHeaders();

    constructor(protected httpClient: HttpClient) {

    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     *
     *
     * @param bookId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiCriticreviewsBookBookIdGet(bookId: number, observe?: 'body', reportProgress?: boolean): Observable<Array<ReviewResponseDto>>;
    public apiCriticreviewsBookBookIdGet(bookId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ReviewResponseDto>>>;
    public apiCriticreviewsBookBookIdGet(bookId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ReviewResponseDto>>>;
    public apiCriticreviewsBookBookIdGet(bookId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (bookId === null || bookId === undefined) {
            throw new Error('Required parameter bookId was null or undefined when calling apiCriticreviewsBookBookIdGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<ReviewResponseDto>>('get',`${this.basePath}/criticreviews/book/${encodeURIComponent(String(bookId))}`,
            {
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiCriticreviewsGet(observe?: 'body', reportProgress?: boolean): Observable<Array<ReviewResponseDto>>;
    public apiCriticreviewsGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ReviewResponseDto>>>;
    public apiCriticreviewsGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ReviewResponseDto>>>;
    public apiCriticreviewsGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<ReviewResponseDto>>('get',`${this.basePath}/criticreviews`,
            {
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param id
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiCriticreviewsIdCommentsPut(id: string, body?: AddCommentToReviewDto, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiCriticreviewsIdCommentsPut(id: string, body?: AddCommentToReviewDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiCriticreviewsIdCommentsPut(id: string, body?: AddCommentToReviewDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiCriticreviewsIdCommentsPut(id: string, body?: AddCommentToReviewDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiCriticreviewsIdCommentsPut.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];

        return this.httpClient.request<any>('put',`${this.basePath}/criticreviews/${encodeURIComponent(String(id))}/comments`,
            {
                body: body,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiCriticreviewsIdDelete(id: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiCriticreviewsIdDelete(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiCriticreviewsIdDelete(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiCriticreviewsIdDelete(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiCriticreviewsIdDelete.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/criticreviews/${encodeURIComponent(String(id))}`,
            {
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param id
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiCriticreviewsIdDislikesDelete(id: string, body?: DislikeReviewDto, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiCriticreviewsIdDislikesDelete(id: string, body?: DislikeReviewDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiCriticreviewsIdDislikesDelete(id: string, body?: DislikeReviewDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiCriticreviewsIdDislikesDelete(id: string, body?: DislikeReviewDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiCriticreviewsIdDislikesDelete.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/criticreviews/${encodeURIComponent(String(id))}/dislikes`,
            {
                body: body,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param id
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiCriticreviewsIdDislikesPut(id: string, body?: DislikeReviewDto, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiCriticreviewsIdDislikesPut(id: string, body?: DislikeReviewDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiCriticreviewsIdDislikesPut(id: string, body?: DislikeReviewDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiCriticreviewsIdDislikesPut(id: string, body?: DislikeReviewDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiCriticreviewsIdDislikesPut.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];

        return this.httpClient.request<any>('put',`${this.basePath}/criticreviews/${encodeURIComponent(String(id))}/dislikes`,
            {
                body: body,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiCriticreviewsIdGet(id: string, observe?: 'body', reportProgress?: boolean): Observable<ReviewResponseDto>;
    public apiCriticreviewsIdGet(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ReviewResponseDto>>;
    public apiCriticreviewsIdGet(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ReviewResponseDto>>;
    public apiCriticreviewsIdGet(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiCriticreviewsIdGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ReviewResponseDto>('get',`${this.basePath}/criticreviews/${encodeURIComponent(String(id))}`,
            {
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param id
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiCriticreviewsIdLikesDelete(id: string, body?: LikeReviewDto, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiCriticreviewsIdLikesDelete(id: string, body?: LikeReviewDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiCriticreviewsIdLikesDelete(id: string, body?: LikeReviewDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiCriticreviewsIdLikesDelete(id: string, body?: LikeReviewDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiCriticreviewsIdLikesDelete.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/criticreviews/${encodeURIComponent(String(id))}/likes`,
            {
                body: body,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param id
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiCriticreviewsIdLikesPut(id: string, body?: LikeReviewDto, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiCriticreviewsIdLikesPut(id: string, body?: LikeReviewDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiCriticreviewsIdLikesPut(id: string, body?: LikeReviewDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiCriticreviewsIdLikesPut(id: string, body?: LikeReviewDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiCriticreviewsIdLikesPut.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];

        return this.httpClient.request<any>('put',`${this.basePath}/criticreviews/${encodeURIComponent(String(id))}/likes`,
            {
                body: body,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param id
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiCriticreviewsIdPut(id: string, body?: UpdateReviewDto, observe?: 'body', reportProgress?: boolean): Observable<ReviewResponseDto>;
    public apiCriticreviewsIdPut(id: string, body?: UpdateReviewDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ReviewResponseDto>>;
    public apiCriticreviewsIdPut(id: string, body?: UpdateReviewDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ReviewResponseDto>>;
    public apiCriticreviewsIdPut(id: string, body?: UpdateReviewDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiCriticreviewsIdPut.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];

        return this.httpClient.request<ReviewResponseDto>('put',`${this.basePath}/criticreviews/${encodeURIComponent(String(id))}`,
            {
                body: body,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiCriticreviewsPost(body?: CreateReviewDto, observe?: 'body', reportProgress?: boolean): Observable<ReviewResponseDto>;
    public apiCriticreviewsPost(body?: CreateReviewDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ReviewResponseDto>>;
    public apiCriticreviewsPost(body?: CreateReviewDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ReviewResponseDto>>;
    public apiCriticreviewsPost(body?: CreateReviewDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

      let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];

        return this.httpClient.request<ReviewResponseDto>('post',`${this.basePath}/criticreviews`,
            {
                body: body,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param userId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiCriticreviewsUserUserIdGet(userId: number, observe?: 'body', reportProgress?: boolean): Observable<Array<ReviewResponseDto>>;
    public apiCriticreviewsUserUserIdGet(userId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ReviewResponseDto>>>;
    public apiCriticreviewsUserUserIdGet(userId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ReviewResponseDto>>>;
    public apiCriticreviewsUserUserIdGet(userId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling apiCriticreviewsUserUserIdGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<ReviewResponseDto>>('get',`${this.basePath}/criticreviews/user/${encodeURIComponent(String(userId))}`,
            {
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }
}
