/**
 * Identity.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';
import {gateway} from "../constants/endpoints";
import {RoleDto} from "../models/role/roleDto";
import {CreateRoleDto} from "../models/role/createRoleDto";



@Injectable({
  providedIn: 'root'
})
export class RolesService {

    protected basePath = gateway;
    public defaultHeaders = new HttpHeaders();


    constructor(protected httpClient: HttpClient) {

    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     *
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiRolesGet(observe?: 'body', reportProgress?: boolean): Observable<Array<RoleDto>>;
    public apiRolesGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<RoleDto>>>;
    public apiRolesGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<RoleDto>>>;
    public apiRolesGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (oauth2) required


        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<RoleDto>>('get',`${this.basePath}/roles`,
            {
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiRolesIdDelete(id: number, observe?: 'body', reportProgress?: boolean): Observable<RoleDto>;
    public apiRolesIdDelete(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RoleDto>>;
    public apiRolesIdDelete(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RoleDto>>;
    public apiRolesIdDelete(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiRolesIdDelete.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<RoleDto>('delete',`${this.basePath}/roles/${encodeURIComponent(String(id))}`,
            {
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiRolesIdGet(id: number, observe?: 'body', reportProgress?: boolean): Observable<RoleDto>;
    public apiRolesIdGet(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RoleDto>>;
    public apiRolesIdGet(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RoleDto>>;
    public apiRolesIdGet(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiRolesIdGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<RoleDto>('get',`${this.basePath}/roles/${encodeURIComponent(String(id))}`,
            {
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param name
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiRolesNameGet(name: string, observe?: 'body', reportProgress?: boolean): Observable<RoleDto>;
    public apiRolesNameGet(name: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RoleDto>>;
    public apiRolesNameGet(name: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RoleDto>>;
    public apiRolesNameGet(name: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (name === null || name === undefined) {
            throw new Error('Required parameter name was null or undefined when calling apiRolesNameGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<RoleDto>('get',`${this.basePath}/roles/${encodeURIComponent(String(name))}`,
            {
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiRolesPost(body?: CreateRoleDto, observe?: 'body', reportProgress?: boolean): Observable<RoleDto>;
    public apiRolesPost(body?: CreateRoleDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RoleDto>>;
    public apiRolesPost(body?: CreateRoleDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RoleDto>>;
    public apiRolesPost(body?: CreateRoleDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];

        return this.httpClient.request<RoleDto>('post',`${this.basePath}/api/roles`,
            {
                body: body,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
