/**
 * Identity.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';
import {gateway} from "../constants/endpoints";
import {UserDto} from "../models/user/userDto";
import {UpdateUserDto} from "../models/user/updateUserDto";
import {RemoveUserFromRoleDto} from "../models/user/removeUserFromRoleDto";
import {AddUserToRoleDto} from "../models/user/addUserToRoleDto";
import {RegisterUserDto} from "../models/user/registerUserDto";



@Injectable({
  providedIn: 'root'
})
export class UsersService {

    protected basePath = gateway;
    public defaultHeaders = new HttpHeaders();

    constructor(protected httpClient: HttpClient) {

    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     *
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiUsersGet(observe?: 'body', reportProgress?: boolean): Observable<Array<UserDto>>;
    public apiUsersGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<UserDto>>>;
    public apiUsersGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<UserDto>>>;
    public apiUsersGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<UserDto>>('get',`${this.basePath}/users`,
            {
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiUsersIdDelete(id: number, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public apiUsersIdDelete(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public apiUsersIdDelete(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public apiUsersIdDelete(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiUsersIdDelete.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<boolean>('delete',`${this.basePath}/users/${encodeURIComponent(String(id))}`,
            {
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiUsersIdGet(id: number, observe?: 'body', reportProgress?: boolean): Observable<UserDto>;
    public apiUsersIdGet(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UserDto>>;
    public apiUsersIdGet(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UserDto>>;
    public apiUsersIdGet(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiUsersIdGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<UserDto>('get',`${this.basePath}/users/${encodeURIComponent(String(id))}`,
            {
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param id
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiUsersIdPut(id: number, body?: UpdateUserDto, observe?: 'body', reportProgress?: boolean): Observable<UserDto>;
    public apiUsersIdPut(id: number, body?: UpdateUserDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UserDto>>;
    public apiUsersIdPut(id: number, body?: UpdateUserDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UserDto>>;
    public apiUsersIdPut(id: number, body?: UpdateUserDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiUsersIdPut.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];

        return this.httpClient.request<UserDto>('put',`${this.basePath}/users/${encodeURIComponent(String(id))}`,
            {
                body: body,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param id
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiUsersIdRolesDelete(id: string, body?: RemoveUserFromRoleDto, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public apiUsersIdRolesDelete(id: string, body?: RemoveUserFromRoleDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public apiUsersIdRolesDelete(id: string, body?: RemoveUserFromRoleDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public apiUsersIdRolesDelete(id: string, body?: RemoveUserFromRoleDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiUsersIdRolesDelete.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];

        return this.httpClient.request<boolean>('delete',`${this.basePath}/users/${encodeURIComponent(String(id))}/roles`,
            {
                body: body,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param id
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiUsersIdRolesPut(id: number, body?: AddUserToRoleDto, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public apiUsersIdRolesPut(id: number, body?: AddUserToRoleDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public apiUsersIdRolesPut(id: number, body?: AddUserToRoleDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public apiUsersIdRolesPut(id: number, body?: AddUserToRoleDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiUsersIdRolesPut.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];

        return this.httpClient.request<boolean>('put',`${this.basePath}/users/${encodeURIComponent(String(id))}/roles`,
            {
                body: body,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiUsersPost(body?: RegisterUserDto, observe?: 'body', reportProgress?: boolean): Observable<UserDto>;
    public apiUsersPost(body?: RegisterUserDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UserDto>>;
    public apiUsersPost(body?: RegisterUserDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UserDto>>;
    public apiUsersPost(body?: RegisterUserDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];

        return this.httpClient.request<UserDto>('post',`${this.basePath}/users`,
            {
                body: body,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param userName
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiUsersUserNameGet(userName: string, observe?: 'body', reportProgress?: boolean): Observable<UserDto>;
    public apiUsersUserNameGet(userName: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UserDto>>;
    public apiUsersUserNameGet(userName: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UserDto>>;
    public apiUsersUserNameGet(userName: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (userName === null || userName === undefined) {
            throw new Error('Required parameter userName was null or undefined when calling apiUsersUserNameGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<UserDto>('get',`${this.basePath}/users/${encodeURIComponent(String(userName))}`,
            {
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }
}
