syntax = "proto3";

option csharp_namespace = "Review.Application.GrpcServices";

import "google/protobuf/wrappers.proto";

message User {
  int32 id = 1;
  string userName = 2;
  google.protobuf.StringValue imageUrl = 3;
}

message Review {
  string id = 1;
  int32 bookId = 2;
  int32 userId = 3;
  int32 rating = 4;
  google.protobuf.StringValue text = 5;
  repeated int32 LikeUserIds = 6;
  repeated int32 DislikeUserIds = 7;
  User user = 9;
}

message GetBookReviewsRequest {
  int32 bookId = 1;
}

message GetBookReviewsResponse {
  repeated Review reviews = 1;
}

service ReviewService {
  rpc GetBookReviews(GetBookReviewsRequest) returns (GetBookReviewsResponse);
}
