<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.3" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.3">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.3" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.3">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
      <PackageReference Include="Serilog.AspNetCore" Version="8.0.2-dev-00336" />
      <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.0-dev-00806" />
      <PackageReference Include="Serilog.Sinks.Debug" Version="2.0.0" />
      <PackageReference Include="Serilog.Sinks.Elasticsearch" Version="10.0.0" />
      <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="6.5.0" />
    </ItemGroup>

</Project>
